// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbglV9gWTpae6a2SX5R6vTOzWMkwzVdy8',
    appId: '1:337091683718:web:04dafb9a5fbd3b32bbf807',
    messagingSenderId: '337091683718',
    projectId: 'cryyptooracle',
    authDomain: 'cryyptooracle.firebaseapp.com',
    storageBucket: 'cryyptooracle.firebasestorage.app',
    measurementId: 'G-0ND8QH8XN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9WekEmRaWRBXRIMj7F0FvoNYjRVoNt2M',
    appId: '1:337091683718:android:6c9cee0f3b4a0067bbf807',
    messagingSenderId: '337091683718',
    projectId: 'cryyptooracle',
    storageBucket: 'cryyptooracle.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7LPoHgCifwrvFijrDZ9oRu-ddSGzSico',
    appId: '1:337091683718:ios:72542c108a17c4fbbbf807',
    messagingSenderId: '337091683718',
    projectId: 'cryyptooracle',
    storageBucket: 'cryyptooracle.firebasestorage.app',
    iosClientId: '337091683718-h99jn9qs6cebe4th4o0j4cs16tj7n17c.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoOracle',
  );
}
